name: README build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '30 01 * * *'

jobs:

# add Snake Animation
  snake:
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: GuillaumeDupuy
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#  add wakatime on readme
  wakatime:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f WAKATIME/requirements.txt ]; then pip install -r WAKATIME/requirements.txt; fi
    - name: run python
      run: |
        python WAKATIME/main.py
      env : 
        WAKATIME_API_KEY : ${{ secrets.WAKATIME_API_KEY }}